# Generated by Django 4.2.3 on 2023-07-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Review', 'Review'), ('Daily', 'Daily')], default='Daily', max_length=30),
        ),
    ]
