# Generated by Django 4.2.3 on 2023-07-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
